# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/harman/May_team_project_I2C_SPI/project_i2C_microblaze/project_i2C_microblaze.srcs/sources_1/bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_v10_0/I2C_Master_Controler_ilmb_v10_0.xci
# IP: The module: 'I2C_Master_Controler_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/harman/May_team_project_I2C_SPI/project_i2C_microblaze/project_i2C_microblaze.gen/sources_1/bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_v10_0/I2C_Master_Controler_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_Master_Controler_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/harman/May_team_project_I2C_SPI/project_i2C_microblaze/project_i2C_microblaze.srcs/sources_1/bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_v10_0/I2C_Master_Controler_ilmb_v10_0.xci
# IP: The module: 'I2C_Master_Controler_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/harman/May_team_project_I2C_SPI/project_i2C_microblaze/project_i2C_microblaze.gen/sources_1/bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_v10_0/I2C_Master_Controler_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_Master_Controler_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
