# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/harman/Basys-3-Master.xdc

# Block Designs: bd/I2C_Master_Controler/I2C_Master_Controler.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler || ORIG_REF_NAME==I2C_Master_Controler} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_microblaze_0_0/I2C_Master_Controler_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_microblaze_0_0 || ORIG_REF_NAME==I2C_Master_Controler_microblaze_0_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_dlmb_v10_0/I2C_Master_Controler_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_dlmb_v10_0 || ORIG_REF_NAME==I2C_Master_Controler_dlmb_v10_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_v10_0/I2C_Master_Controler_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_ilmb_v10_0 || ORIG_REF_NAME==I2C_Master_Controler_ilmb_v10_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_dlmb_bram_if_cntlr_0/I2C_Master_Controler_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==I2C_Master_Controler_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_ilmb_bram_if_cntlr_0/I2C_Master_Controler_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==I2C_Master_Controler_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_lmb_bram_0/I2C_Master_Controler_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_lmb_bram_0 || ORIG_REF_NAME==I2C_Master_Controler_lmb_bram_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_mdm_1_0/I2C_Master_Controler_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_mdm_1_0 || ORIG_REF_NAME==I2C_Master_Controler_mdm_1_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_clk_wiz_1_0/I2C_Master_Controler_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_clk_wiz_1_0 || ORIG_REF_NAME==I2C_Master_Controler_clk_wiz_1_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_rst_clk_wiz_1_100M_0/I2C_Master_Controler_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==I2C_Master_Controler_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_xbar_0/I2C_Master_Controler_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_xbar_0 || ORIG_REF_NAME==I2C_Master_Controler_xbar_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_microblaze_0_axi_periph_0/I2C_Master_Controler_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_microblaze_0_axi_periph_0 || ORIG_REF_NAME==I2C_Master_Controler_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_axi_uartlite_0_0/I2C_Master_Controler_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_axi_uartlite_0_0 || ORIG_REF_NAME==I2C_Master_Controler_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/I2C_Master_Controler/ip/I2C_Master_Controler_I2C_Master_0_3/I2C_Master_Controler_I2C_Master_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Master_Controler_I2C_Master_0_3 || ORIG_REF_NAME==I2C_Master_Controler_I2C_Master_0_3} -quiet] -quiet

# XDC: c:/harman/May_team_project_I2C_SPI/project_i2C_microblaze/project_i2C_microblaze.gen/sources_1/bd/I2C_Master_Controler/I2C_Master_Controler_ooc.xdc
